// maclo - an ML/I macro processor ported to Go
// Copyright (c) 2026 Michael D Henderson.
// All rights reserved.

package sema_test

import (
	"strings"
	"testing"

	"github.com/mdhender/maclo/pkg/l/ast"
	"github.com/mdhender/maclo/pkg/l/cst"
	"github.com/mdhender/maclo/pkg/l/scanner"
	"github.com/mdhender/maclo/pkg/l/sema"
)

// check runs the whole front end over a source and returns the table and the
// diagnostics as one string.
func check(t *testing.T, src string) (*sema.Table, string) {
	t.Helper()
	toks, errs := scanner.Scan([]byte(src))
	f, perrs := cst.Parse(toks)
	prog, berrs := ast.Build(f)
	if errs.HasErrors() || perrs.HasErrors() || berrs.HasErrors() {
		t.Fatalf("the source does not parse:\n%v\n%v\n%v", errs, perrs, berrs)
	}
	tab, cerrs := sema.Check(prog)
	var msgs []string
	for _, e := range cerrs.Sorted() {
		msgs = append(msgs, e.Msg)
	}
	return tab, strings.Join(msgs, "\n")
}

// program wraps a VARS body and a MAIN body in the frame every L source needs.
func program(vars, main string) string {
	return "PRGSTART\nSECTION VARS,//V//\n" + vars + "\nENDSECT VARS\n" +
		"SECTION MAIN,//M//\n" + main + "\nENDSECT MAIN\nPRGEND\n"
}

// TestForwardReferencesResolve. A name may be used before it is declared
// anywhere in L - a GO TO in one SECTION reaching a label in another is
// ordinary - so collection has to finish before references are looked at.
func TestForwardReferencesResolve(t *testing.T) {
	_, msgs := check(t, program(
		"        DEC TOTAL INIT 0",
		"[BEGIN] GO TO LATER\n        SET TOTAL = 1\n[LATER] GO TO BEGIN"))
	if msgs != "" {
		t.Errorf("unexpected diagnostics:\n%s", msgs)
	}
}

// TestUndefinedIsReportedOnceWithAllItsUses. Reporting at the point of use
// would print the same name five times in a file that branches to it five
// times, which is the behaviour pkg/lowl/assembler avoids too.
func TestUndefinedIsReportedOnceWithAllItsUses(t *testing.T) {
	_, msgs := check(t, program(
		"        DEC TOTAL INIT 0",
		"[BEGIN] GO TO NOWHER\n        SET TOTAL = 1\n        GO TO NOWHER\n        GO TO BEGIN"))
	if n := strings.Count(msgs, "NOWHER is not declared"); n != 1 {
		t.Errorf("NOWHER reported %d times, want 1:\n%s", n, msgs)
	}
	if !strings.Contains(msgs, "here and at") {
		t.Errorf("the second use was not listed:\n%s", msgs)
	}
}

// TestBlockSizeConstantsAreDerived. The manual names four of them and the
// logic of ML/I declares five blocks, so deriving the name from the
// declaration is both less code and more correct than a list.
func TestBlockSizeConstantsAreDerived(t *testing.T) {
	tab, msgs := check(t, program(
		"BLOCKDEC DIB,//A BLOCK THE MANUAL'S LIST OMITS//\n        DEC ENDPT INIT NULLPT\nENDBLOCK DIB",
		"[BEGIN] SET ENDPT = DIBSZ\n        GO TO BEGIN"))
	if msgs != "" {
		t.Errorf("unexpected diagnostics:\n%s", msgs)
	}
	sym, ok := tab.Lookup("DIBSZ")
	if !ok {
		t.Fatal("DIBSZ was not derived from BLOCKDEC DIB")
	}
	if sym.Kind != sema.Constant {
		t.Errorf("DIBSZ is a %s, want a constant", sym.Kind)
	}
}

// TestHETablesLabelsAreConditional. ERBLOC, GHSHTB and SVEC are generated by
// the HETABLES statement and written nowhere. Seeding them only when the
// statement is present is what keeps the allowance checked rather than silent.
func TestHETablesLabelsAreConditional(t *testing.T) {
	with := "PRGSTART\nSECTION VARS,//V//\n        DEC HASHPT INIT NULLPT\nENDSECT VARS\n" +
		"SECTION MAIN,//M//\n[BEGIN] SET HASHPT = AD(GHSHTB)PT\n        GO TO BEGIN\nENDSECT MAIN\n" +
		"SECTION DELS,//D//\nHETABLES\nENDSECT DELS\nPRGEND\n"
	if _, msgs := check(t, with); msgs != "" {
		t.Errorf("with HETABLES, unexpected diagnostics:\n%s", msgs)
	}

	without := strings.Replace(with, "HETABLES\n", "", 1)
	if _, msgs := check(t, without); !strings.Contains(msgs, "GHSHTB is not declared") {
		t.Errorf("without HETABLES, GHSHTB was allowed anyway:\n%s", msgs)
	}
}

// TestChainVariablesCountAsUsed. CHANPT and CHLINK are read and written by the
// loop without being named, so a program that declares them and never writes
// them by hand must not be told they are unused.
func TestChainVariablesCountAsUsed(t *testing.T) {
	_, msgs := check(t, program(
		"        DEC CHANPT INIT NULLPT\n        DEC CHLINK INIT 0\n        DEC DELPT INIT NULLPT",
		"[BEGIN] CHAIN FROM DELPT EXIT DONE\n        ENDCH\n[DONE]  GO TO BEGIN"))
	if msgs != "" {
		t.Errorf("unexpected diagnostics:\n%s", msgs)
	}
}

// TestEntryLabelsAreNotUnused. The initialisation code branches to BEGIN, or
// to MBEGIN when INVALS has been deleted from the map. Nothing in L branches
// to either, and saying so on every run would be true and useless.
func TestEntryLabelsAreNotUnused(t *testing.T) {
	_, msgs := check(t, program(
		"        DEC TOTAL INIT 0",
		"[BEGIN] SET TOTAL = 0\n[MBEGIN] SET TOTAL = 1"))
	if strings.Contains(msgs, "BEGIN") {
		t.Errorf("an entry label was reported:\n%s", msgs)
	}
}

func TestKindMismatches(t *testing.T) {
	for _, tc := range []struct {
		name, vars, main, want string
	}{
		{"AD naming a program label", "        DEC DESTPT INIT NULLPT",
			"[BEGIN] SET DESTPT = AD(BEGIN)PT", "used as the argument of AD"},
		{"a branch to a variable", "        DEC TOTAL INIT 0",
			"[BEGIN] SET TOTAL = 0\n        GO TO TOTAL", "used as a branch target"},
		{"a call of a variable", "        DEC TOTAL INIT 0",
			"[BEGIN] SET TOTAL = 0\n        CALL TOTAL", "used as the subroutine of a CALL"},
		{"a value that is a label", "        DEC TOTAL INIT 0",
			"[BEGIN] SET TOTAL = BEGIN", "used as a value"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, msgs := check(t, program(tc.vars, tc.main))
			if !strings.Contains(msgs, tc.want) {
				t.Errorf("diagnostics are\n%s\nwant one mentioning %q", msgs, tc.want)
			}
		})
	}
}

// TestTypeIsRecordedAndNotEnforced. The suffix of a name gives its type
// (lmap.txt 3.2). This pass writes it down and checks nothing with it, and
// that is deliberate: the manual's operand rules are subtler than the suffix,
// and a half-done type check is worse than none.
func TestTypeIsRecordedAndNotEnforced(t *testing.T) {
	tab, msgs := check(t, program(
		"        DEC FLGSW INIT 0\n        DEC BASEPT INIT NULLPT\n        DEC COUNT INIT 0",
		"[BEGIN] SET COUNT = BASEPT\n        SETSW FLGSW = COUNT\n        GO TO BEGIN"))
	if msgs != "" {
		t.Errorf("a type was enforced:\n%s", msgs)
	}
	for name, want := range map[string]ast.DataType{
		"FLGSW": ast.SW, "BASEPT": ast.PT, "COUNT": ast.NM,
	} {
		sym, ok := tab.Lookup(name)
		if !ok {
			t.Fatalf("%s is missing", name)
		}
		if sym.Type != want {
			t.Errorf("%s is %s, want %s", name, sym.Type, want)
		}
	}
}
